server:
  port: 8080

spring:
  application:
    name: ai-assistant-naive

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

services:
  hr:
    base-url: http://localhost:8084
  deployment:
    base-url: http://localhost:8082
