spring:
  application:
    name: ai-assistant-mcp

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

    mcp:
      client:
        enabled: true
        streamable-http:
          connections:
            hr:
              url: http://localhost:8084
            deployment:
              url: http://localhost:8082
            notification:
              url: http://localhost:8083

logging:
  level:
    io:
      modelcontextprotocol: DEBUG